repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --force-exclude --fix --exit-non-zero-on-fix
        language: system
        types_or: [python]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: system
        types: [python]
        require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy
        args: [src/extra_checks, tests]
        pass_filenames: false
      - id: django-check
        name: django check
        language: system
        entry: env PYTHONPATH=src:. DJANGO_SETTINGS_MODULE=tests.settings django-admin
        args: [check, --fail-level, CRITICAL]
        pass_filenames: false
